deivid-rodriguez/byebug

- lib/byebug/commands/break.rb
- test/commands/break_test.rb
- test/commands/help_test.rb
Not sure I understood the "add [#106](https://github.com/deivid-rodriguez/byebug/issues/106) to the help" part. And not sure if I came up with a good way to accomplish it.
> Fix break description.

- GUIDE.md
> Fix GUIDE.md

- test/interfaces/script_interface_test.rb
Just adding some test coverage to an untested file.
> Add test coverage to script interface test

- lib/byebug/commands/var/const.rb
- lib/byebug/helpers/frame.rb
- lib/byebug/helpers/thread.rb
- lib/byebug/helpers/var.rb
it looks like most of my recent changes were lost during commands' re-architecture :(
Restoring them.
Do you think we should add some tests to void such problem in future, or you do not expect to do this again?
> restoring changes which were lost in the latest rewrite/merge

- GUIDE.md
[skip ci]
Follow-up to #162.
Cheers!
> GUIDE.md: remove `exit` command + minor grammar fixes

- CONTRIBUTING.md
> Change minitest_runner.rb name in CONTRIBUTING.md

- lib/byebug/processors/control_processor.rb
- lib/byebug/processors/script_processor.rb
As We discussed in: https://github.com/deivid-rodriguez/byebug/commit/da69f65a, adding some missing requires.
> Adding missing require to processor files

- README.md
Expanded the Usage example to make the workflow a bit clearer.
> Added an example to the usage

- lib/byebug/commands/irb.rb
See #197 
Test results are the same on this branch as on master.
I tested manually with https://github.com/josephks/bug_demo and this fix works.  I'm not sure how to write an automated test for this.
> Fix issue 197 by clearing and restoring ARGV

- .travis.yml
- Gemfile
- Gemfile.lock
- appveyor.yml
Trying the fix for rake-compiler/rake-compiler#123.
> Bump rake-compiler development dependency

- CHANGELOG.md
- Gemfile.lock
- lib/byebug/commands/break.rb
- lib/byebug/commands/info/file.rb
- lib/byebug/version.rb
- test/commands/break_test.rb
- test/commands/info_test.rb
> Windows path improvements

- appveyor.yml
> Force bundler 1.11.2 in Appveyor

- CHANGELOG.md
- lib/byebug/remote.rb
> Don't confirm on the remote side

- CHANGELOG.md
- lib/byebug/core.rb
- lib/byebug/runner.rb
- test/commands/edit_test.rb
- test/rc_test.rb
- test/support/temporary.rb
> Rc loading with nil home

- .travis.yml
- Dockerfile
- lib/byebug/history.rb
- lib/byebug/interfaces/local_interface.rb
- test/commands/history_test.rb
> Libedit improvements

- bin/byebug
- byebug.gemspec
- lib/byebug/core.rb
- lib/byebug/helpers/path.rb
- lib/byebug/printers/base.rb
- lib/byebug/printers/plain.rb
- script/minitest_runner.rb
Improves path handling and file ignoring. 
[1]: https://github.com/blog/1506-closing-issues-via-pull-requests
> Better file ignores & path handling

- GUIDE.md
> Doc improvements

- lib/byebug/commands/irb.rb
- lib/byebug/commands/restart.rb
- lib/byebug/helpers/bin.rb
- lib/byebug/runner.rb
- script/minitest_runner.rb
- test/commands/restart_test.rb
- test/support/test_case.rb
More realistic tests for runner and restart.
> Improve runner and restart commands

- .rubocop.yml
- lib/byebug/commands/info/file.rb
- lib/byebug/helpers/string.rb
- lib/byebug/runner.rb
- test/printers/plain_test.rb
- test/support/test_case.rb
- test/support/utils.rb
> Preparation for more realworld tests

- CHANGELOG.md
- Gemfile.lock
- lib/byebug/version.rb
It's been a while, let's get the latest improvements out there.
> 9.1.0 release

- appveyor.yml
Update appveyor.yml
1. Added trunk as an allowed failure
2. Shorted PATH
3. Removed fast finish
You might also be asked to:
[autoclose]: https://github.com/blog/1506-closing-issues-via-pull-requests
> Update appveyor with trunk, cleanup

- appveyor.yml
I moved the build from BinTray to Appveyor
> Change trunk download from BinTray to Appveyor

- appveyor.yml
/cc @MSP-Greg 
Can you review?
> Remove lines ruby trunk doesn't like

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- README.md
- ext/byebug/byebug.h
- script/ci.sh
Adding macOS builds into travis matrix
> Setup osx travis builds

- .travis.yml
- appveyor.yml
- script/ci.sh
Also use the folder bundler 2 will use by default.
> Fix travis caching

- GUIDE.md
- README.md
> Installation note

- .circleci/config.yml
- .travis.yml
- GUIDE.md
- README.md
- Ruby_Grant_2014_Report.md
- appveyor.yml
- docker/manager.rb
- tasks/dev_utils.rb
- test/commands/finish_test.rb
- test/post_mortem_test.rb
- test/support/test_case.rb
Refs: https://github.com/deivid-rodriguez/byebug/issues/290.
> Ensure finish works inside autoloaded files

- docker/Dockerfile
Follow up to overcommit removal.
> Remove stuff no longer needed to Dockerfile

- .simplecov
- test/minitest_runner_test.rb
Extracting unrelated changes from other PR's to simplify diffs.
> Simplecov simplifications

- .mdlrc
- .rubocop.yml
- .simplecov
- CHANGELOG.md
- GUIDE.md
- appveyor.yml
- docker/Dockerfile
- lib/byebug/command.rb
- lib/byebug/printers/texts/base.yml
- lib/byebug/subcommands.rb
- test/commands/continue_test.rb
- test/commands/debug_test.rb
- test/commands/down_test.rb
- test/commands/finish_test.rb
- test/commands/frame_test.rb
- test/commands/info_test.rb
- test/commands/kill_test.rb
- test/commands/list_test.rb
- test/commands/method_test.rb
- test/commands/next_test.rb
- test/commands/up_test.rb
- test/commands/var_test.rb
- test/commands/where_test.rb
- test/printers/plain_test.rb
- test/processors/command_processor_test.rb
- test/support/assertions.rb
- test/support/utils.rb
Another PR to extract unrelated changes from other branches.
> Normalizing string literals

- CHANGELOG.md
- GUIDE.md
- lib/byebug/core.rb
- lib/byebug/helpers/bin.rb
- lib/byebug/runner.rb
- test/commands/break_test.rb
- test/helpers/bin_helper_test.rb
- test/rc_test.rb
- test/runner_test.rb
- test/support/test_case.rb
Some more changes extracted from big PR's to simplify those.
EDIT: This ended up including a bug fix or feature (not sure how to call it). Very minor in any case.
> Minor test tweaks

- appveyor.yml
Some tweaks to our appveyor config.
> Tweak appveyor

- appveyor.yml
- lib/byebug/remote/client.rb
- test/support/remote_debugging_tests.rb
> Test against ruby 2.5 on Appveyor

- .codeclimate.yml
- Rakefile
- docker/manager.rb
> Move rubocop check to CircleCI

- LICENSE
- code_of_conduct.md
Signaled by [tidelift](https://tidelift.com/), and making Github not showing it properly.
> Try to fix license discrepancy

- README.md
I'm proud and grateful for it, you should subscribe.
> Mention Tidelift in README

- CHANGELOG.md
And standarize it a bit more according to keepachangelog.com guidelines.
> Add missing changelog section

- CHANGELOG.md
Curates the changelog a bit, mainly by fixing broken links.
> Link changelog issues and prs

- .circleci/config.yml
- .travis.yml
- Gemfile.lock
- appveyor.yml
- docker/Dockerfile
- docker/manager.rb
> Test against latest rubies

- .circleci/config.yml
- Rakefile
- docker/manager.rb
This PR fixes the nightly job that builds a ruby head image to test byebug against, as mentioned in #520.
> Fix nightly job

- CHANGELOG.md
- Gemfile.lock
- lib/byebug/version.rb
Almost a year without cutting master, let's do it!
Kudos to [Tidelift](https://tidelift.com/subscription/pkg/rubygems-byebug?utm_source=rubygems-byebug&utm_medium=11.0.0_release_ticket) for contributing to a more sustainable open source world! :heart:
> Get ready for 11.0.0 release

- .github/FUNDING.yml
By using the new github feature.
> Make funding more visible

- README.md
> Clarify best MRI version support in README

- ext/byebug/byebug.c
I want to get rid of this special case. So I'll add a warning for now and if nobody complains in a few releases, I'll drop the whole thing. Otherwise I'll try to report and get the underlying issue fixed.
> Add a warning for a case that should be fixed

- README.md
The idea is to increase the visibility of the subscription.
> README updates for Tidelift

- README.md
Update a readme file with new commands that were added in previous releases.
> Readme: add new commands

- Gemfile
- Gemfile.lock
> Add rexml as a dependency temporarily

- test/support/remote_debugging_tests.rb
> Show errors if subprocess fails

- .bundle/config
- .gitignore
- docker/Dockerfile
To make running tests more consistent.
> Commit a bundler config file

- .github/workflows/build.yml
- .github/workflows/build_head_images.yml
- .github/workflows/fedora.yml
For a more deterministic build.
> Lock checkout action to v2

- .github/workflows/daily.yml
- .github/workflows/fedora.yml
- .github/workflows/ubuntu.yml
Just to have more meaningful and consistent names.
> Rename some stuff in CI

- test/support/remote_debugging_tests.rb
And possibly fix random hangs.
> Refactor remote debugging tests

- exe/byebug
> exe/byebug: drop relative require

- appveyor.yml
The previous one is no longer available.
> Use another rb-readline fork

- README.md
As per https://forum.tidelift.com/t/new-urls-for-project-badges/288.
> Fix Tidelift badge
