deivid-rodriguez/byebug

lib/byebug/commands/break.rb

Necessary for debugger-xml, since it has to pass that information to IDE

Pass file/line to 'break.created' print

---

CHANGELOG.md
ext/byebug/breakpoint.c
test/commands/break_test.rb
test/support/test_case.rb

[It](https://github.com/deivid-rodriguez/byebug/issues/122) took less than I expected. If I haven't introduced any new issues with this commit, that is. And running `CCop` failed, not sure what this means:
```
Running CCop...
Inspecting 5 files
rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_size - ext/byebug/byebug.c_corrected
/home/yuri/_/byebug/tasks/ccop.rb:28:in `block (2 levels) in <top (required)>'
/home/yuri/_/byebug/tasks/ccop.rb:23:in `each'
/home/yuri/_/byebug/tasks/ccop.rb:23:in `block in <top (required)>'
Tasks: TOP => default => ccop
(See full trace by running task with --trace)
```
By the way, you can contribute to [this question](http://stackoverflow.com/questions/28608097/how-do-i-debug-ruby-c-extensions) if you've got anything to add.

Fix setting breakpoints on module methods.

---

.gitignore
lib/byebug/commands/thread.rb
lib/byebug/commands/var.rb
lib/byebug/printers/plain.rb
test/commands/stepping_test.rb

the debugger-xml+byebug+RubyMine integration is not complete, but this is the first problem I've found and (I hope) fixed.
For some reasons I was unable to run indent command on Mac
IMHO it would be nice to known what exact version of the utility we are supposed to use.

thread list command fixed to work with debugger-xml

---

lib/byebug/commands/eval.rb
lib/byebug/commands/frame.rb

I've added some information debugger-xml needs from byebug to remove monkey-patching from debugger-xml.
I've made a small change in var.rb which will not allow us to remove monkey-patching completely because we do provide additional sub-commands and replace couple methods (see https://github.com/astashov/debugger-xml/blob/master/lib/byebug/commands/variables.rb)  Any ideas how to improve that is welcome.
Also debugger-xml monkey-patches several commands to make them "unsupported" (e.g. https://github.com/astashov/debugger-xml/blob/master/lib/byebug/commands/help.rb)
Again any ideas how to fix this w/o monkey-patching are welcome ;)

No more monkey patching

---

lib/byebug/helpers/parse.rb

for frame cmd to work correctly, 
adjust_frame() at line 29 (in  [byebug/commands/frame.rb ](https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/commands/frame.rb)) should be invoked, 
but, it doesn't, because pos is assined to nil  and execute() returns at line 27.
```
20    def execute()
~
26       pos, err = get_int(@match[1], 'Frame')
27             return errmsg(err) unless pos
28
29             adjust_frame(pos, true)
```
The nil comes from the statement at line 15 (in [byebug/helpers/parse.rb](https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/helpers/parse.rb)),
due to the regular expression at line 13, which is evaluated as false, given str negative number.
```
12    def get_int(str, cmd, min = nil, max = nil)
13      if str !~ /\A[0-9]+\z/
14 …
```

make frame cmd work with negative arg

---

lib/byebug/remote.rb

It seems just a typo in this commit: https://github.com/deivid-rodriguez/byebug/commit/90cdfcc9cee8ba6362bad2185390cbe4fa85845d
Using the same var in the two places kills one connect when another is opened. Detected the problem while using sublime-ruby-debugger.
I just changed to use a local var (igual was before that commit), and it fixes everething for me.

Fix the use of both control and normal connections

---

README.md

As per commit 76702a2:
https://github.com/deivid-rodriguez/byebug/commit/76702a255b9edf754cdd51
c238b76af132b784ec
Thanks for the great gem!

Remove `exit` command from the README [skip ci]

---

lib/byebug.rb
lib/byebug/attacher.rb
test/test_helper.rb

When running tests, it is nice to both have the `byebug` command available, and to have the tests start up really fast.
Fixes #166.

Don't load entire library up front

---

CHANGELOG.md
ext/byebug/byebug.c
lib/byebug/commands/continue.rb
lib/byebug/interfaces/local_interface.rb
test/commands/continue_test.rb
test/interfaces/local_interface_test.rb

Fixes https://github.com/deivid-rodriguez/byebug/issues/144.
I couldn't find out how to avoid SEGV in tests and what a correct fix would be. I'm just sharing my idea.
`Byebug.start` enables tracepoints and they are left enabled after `continue`. If tracepoints are enabled, it gets slow. In fact, this branch does not change things slow after `continue`. I want to disable them while I'm not debugging.
I think we can disable tracepoints after `continue` or ^D and enable them again when `byebug` or `debugger` is called. Is there any reason to keep tracepoints enabled all the time?

Disable tracepoints after continue

---

GUIDE.md

It was calling: 'set trace' instead of 'set linetrace'.

Fixing setting line trace name on example

---

lib/byebug/runner.rb

lib/byebug/option_setter.rb:59:in `block in stop': undefined method `stop=' for #<Byebug::Runner:0x0000011102abe0 @stop=true, @quit=true> (NoMethodError)

option `-s` broken

---

CHANGELOG.md
ext/byebug/breakpoint.c

because xcode clang define bool macro
Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stdbool.h:31:14: note:
expanded from macro 'bool'
#define bool _Bool

change variable name bool

---

ext/byebug/byebug.c

This is very minor issue.
`Byebug.started?` return `false` when breakpoints hasn't been set.
`Byebug.started?` return `0` when some breakpoints has been set.

Return true as boolean if byebug is already started

---

GUIDE.md

History file name had changed in https://github.com/deivid-rodriguez/byebug/commit/023eac2127a2a90c4d14b38499628fbbde82df3d .

GUIDE.md: change history file name

---

GUIDE.md

Change "require 'byebug'" to require "'byebug/core'."
Issue: https://github.com/deivid-rodriguez/byebug/issues/195

Guide.md: update remote debugging instructions

---

.travis.yml

2.1.8 and 2.2.4 cannot yet be installed there.

Allow OSX to fail until fixed

---

lib/byebug/interfaces/local_interface.rb

I've been testing this for a few weeks to debug programs that read from stdin and write to stdout. This is the way I'm accustomed to other debuggers working out of the box.

Use IO.console for readline over STD{IN,OUT,ERR}.

---

GUIDE.md

The `eval` command works better for printing out variables than `p` since `p` will first print, and then the result of `p` is again printed.
The result is that all output gets displayed twice.
This simply changes the `p` to `eval` in the guide.

Update Guide.md to use 'eval' instead of 'p'

---

Gemfile
Gemfile.lock
appveyor.yml

Using `rake-compiler` 0.9.6 breaks Windows build.

Fix windows build

---

ext/byebug/byebug.h

`catchpoint_hit_count` is deleted by
a3eb12c58cd1f1bc3f63e26c0af71a8dc46641df

Remove not defined function from byebug.h

---

lib/byebug/remote.rb

Resend of previous pull request changing require_relative to require.

Fix creation of remote control processor

---

ext/byebug/byebug.c
test/commands/continue_test.rb

Fixes test 1 of https://github.com/deivid-rodriguez/byebug/issues/194.
We should keep tracepoints enabled to trace lines.

Don't stop byebug with linetrace enabled

---

.travis.yml

"clang: error: unknown argument: '-fexcess-precision=standard'"
occurs when "compiling ../../../../ext/byebug/breakpoint.c".
The reason why compile error occurs is that we use ruby build
by gcc and compile byebug with clang.
"mkmf" uses values of `RbConfig` module which were defined
when ruby is built.
This commit make "env CC" match build information of ruby.
ref: https://github.com/ruby/ruby/blob/v2_3_0/tool/mkconfig.rb

Fix build failure on "ruby-head" x "CC=clang"

---

CHANGELOG.md
lib/byebug/helpers/file.rb
test/commands/continue_test.rb

Fix for test 2 and 3 in https://github.com/deivid-rodriguez/byebug/issues/194.
We can't open a file named "(eval)". So byebug should skip to read its line on linetrace.

Skip to get a line in eval context

---

lib/byebug/interfaces/local_interface.rb
lib/byebug/interfaces/script_interface.rb
test/interfaces/script_interface_test.rb

This makes it possible to use http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#method-i-capture_io to capture the output of byebug in tests (more context: https://github.com/deivid-rodriguez/pry-byebug/pull/90)

Use global instead of constant stdin, stdout and stderr

---

byebug.gemspec

Using an spdx license identifier makes it easier for tools like https://github.com/pivotal/LicenseFinder to manage gem licenses.

Use http://spdx.org/licenses identifier in gemspec.

---

lib/byebug/remote.rb

I didn't find docs or tests for `start_server` taking a block;
not sure how you intended that to be used and whether you'll consider this backward-compatible.
This allows `wait_connection=true` to be meaningfully used with `port=0`.
(If it doesn't return until a client connects,
but a client can't know what port it will listen on,
then here is the only chance to tell the client what port to use.)
My (ab)use case is debugging an app with many background workers.
I wanted to use remote byebug, but I'd have to make each worker listen on a different port, and connect to them all.  (To make things worse, workers are sometimes created/destroyed.)
Instead I wrote this kludge: https://gist.github.com/cben/4d4851f63ded79b74d1cb162422ff13b
which at the breakpoint starts a server and a new terminal …

Byebug.start_server: yield later, when actual_port is known

---

lib/byebug/commands/enable/breakpoints.rb

It said "Disable" instead of "Enable".

Fix enable breakpoint short description

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.mdlrc

There's recently been some friction about how to get changes merged in. Let's add issue and PR templates to try to reduce that.
Credits to the RuboCop project for providing the starting point of these templates.

Add templates for Github issues and PRs

---

CHANGELOG.md
lib/byebug/commands/delete.rb
lib/byebug/helpers/toggle.rb
lib/byebug/printers/texts/base.yml
lib/byebug/printers/texts/plain.yml
test/commands/break_test.rb
test/commands/condition_test.rb
test/commands/delete_test.rb
test/commands/disable_test.rb
test/commands/enable_test.rb

Supersedes #281.
Include some extra minor changes in the test files and the correction of one bug the other PR was introducing.
@rocky Since I haven't tried this against a real program, just against byebug test suite, feel free to try this branch and tell me if it satifies your needs.

Better messages for breakpoint management

---

.travis.yml
README.md
test/support/coverage.rb

Closes #69.
You might also be asked to:
[1]: https://github.com/blog/1506-closing-issues-via-pull-requests

Add Atom plugin to README

---

.travis.yml

Workaround to fix ruby-head + libedit Travis matrix entry.
[1]: https://github.com/blog/1506-closing-issues-via-pull-requests

Fix ruby-head + libedit travis

---

CHANGELOG.md
lib/byebug/frame.rb
test/commands/where_test.rb

I was getting an error message like the following when using the `where` command
`*** undefined method `included' for class `SomeController'`
which I managed to track down to a module being mixed into a controller that was using `def self.included` to add a `prepend_around_action` with a block.  I also managed to simplify the test case into the regression test I have added in this PR.
The reason why instance_exec was causing problems is that it calls the block with a different receiver, so `self` in that context won't have the method the block was defined in.
Use the frame_class since instance_exec doesn't change it, so the instance method can still be found from the blocks frame.
* Unhandled exceptions in commands don't result in a stack trace that can easily find where the command …

Fix where command for instance_exec blocks

---

CHANGELOG.md
lib/byebug/commands/restart.rb
test/commands/restart_test.rb

I modified 'restart' command to run on Windows.

Fix restart

---

.rubocop.yml
.travis.yml
CHANGELOG.md
README.md
appveyor.yml
byebug.gemspec
lib/byebug/frame.rb
tasks/dev_utils.rb

This PR drops official & unofficial support for Ruby 2.0 & Ruby 2.1. Supersedes #336.

Drop support for old rubies

---

appveyor.yml

This PR should get Appveyor 2.4.1 build green again.
Full credit to @MSP-Greg for the tip :heart:.

Fix Appveyor 2.4.1 build

---

Gemfile.lock

This PR bumps the version of bundler in our Gemfile.lock file to 1.15.4.

Bump bundler to 1.15.4 in Gemfile.lock

---

.travis.yml
README.md

Adds `fast_finish` flag to Travis CI, so PR's get a green or red status faster. Also changes the Travis badge URL since the old one does not get updated instantly, apparently.

Add travis fast finish

---

test/commands/where_test.rb
test/support/test_case.rb

Default tmpdir on macOS is is a symlink pointing somewhere in
`/private/...`.  Because of this in the testsuite we should
always use realpaths since byebug outputs those by default.
Without the fix it is full of failures like https://gist.github.com/bak1an/4f6bdbbadfe96c53bd9d16dd86a87779
The PR also disables `WhereWithNotDeeplyNestedPathsTest` for `darwin` since default `$TMPDIR` on macOS nowadays is something like `/var/folders/5g/s0v3cc2x34ddw3ydhyvkryvr0000gn/T/` (which has realpath `/private/var/folders/5g/s0v3cc2x34ddw3ydhyvkryvr0000gn/T/`). This is the opposite of `not deeply nested` and just fails.

Fixup the testsuite fails on macOS

---

script/minitest_runner.rb
test/support/assertions.rb
test/support/test_case.rb

Currently appveyor build against `ruby-head` deadlocks. That means that we have a bug there, but also that appveyor takes about an hour to send back to green status to GitHub PR's (due to https://github.com/appveyor/ci/issues/1960).
I don't expect byebug test run to ever take longer than 3 minutes, so let's detect those situations and fail early.
This PR also adds some little tweaks to the tests.
Credits to @MSP-Greg for the idea and implementation!

Detect timeouts and other test improvements

---

lib/byebug/breakpoint.rb

On Ruby 2.5, format of `RubyVM::InstructionSequence#disasm`
will be changed. By this change we can not detect which
line is valid to set breakpoints. On the other hand
Ruby 2.5 will introduce new methods
* `RubyVM::InstructionSequence#each_child`
Iterate all direct child instruction sequences.
* `RubyVM::InstructionSequence#trace_points`
Return trace points in the instruction sequence.
see: https://github.com/ruby/ruby/blob/9fe26ef8de1ae047a4d775ce74878a0aeb01a19b/NEWS
We can detect potential_lines by these methods.
So this commit defines new methods and call each_child &
trace_points if these methods are implemented.
Thanks to Koichi Sasada (ko1) for investigation, implemention of
new methods for Ruby and concept implementation for byebug.
This PR is a part of Ruby 2.5 support. I will …

Fix how to detect potential_lines

---

test/commands/break_test.rb

When stopped by breakpoint for an empty method
whose body is empty, the line of `def method_name`
would be displayed.

Add breakpoints test cases for empty methods

---

test/commands/finish_test.rb
test/commands/where_test.rb

Not turning warnings on because external gems (`thor`) have warnings and the whole thing seems to abort when that happens on appveyor.

~Turn on and~ fix ruby warnings during tests

---

.travis.yml

Supersedes #420 (same with less debug commits and a more adequate branch name).

Bump rubies on macos

---

byebug.gemspec
exe/byebug

And check for presence of the lib dir before adding it.
This is the default in bundler's generated gems, so I think it should work best.

Move LOAD_PATH manipulation to gemspec

---

.travis.yml

Shellcheck is now run by a separate codeclimate service, so we don't
need it in Travis.

Remove shellcheck installation from Travis config

---

CHANGELOG.md
Gemfile.lock
lib/byebug/version.rb

Get ready for 10.0.0 release

---

appveyor.yml

Appveyor badge is considering ruby-head because (I think) allowed failures are not being properly specified.

Fix allowed failures incorrectly specified

---

README.md

Added `interrupt`, `untracevar`, and `where`. Reordered `delete` and `debug`

Added missing commands, reordered by alpha

---

CHANGELOG.md
ext/byebug/byebug.c
ext/byebug/byebug.h
ext/byebug/context.c
ext/byebug/threads.c

When we use byebug and debase gem simultaneously, there are conflict because extern function name is conflict each other.
For example, with byebug and debase gem, if we use `byebug` method to debug code, the following error is occured (this is the same issue as #200 #360 )
```
NoMethodError (undefined method `step_out' for #<Byebug::Context:0x007fa4608278d0>)
```
This is because both gem have extern function `Init_context` and `context_create` and if we call these function in byebug gem, it calls debase's function. (Maybe other development gem use these function name, because `context` is commonly used variable name)
This PR solve by renaming function.

Rename function to prevent conflict to debase

---

.circleci/config.yml
docker/Dockerfile

And also move it to circleCI since install time is negigible and upgrading is easier.

Pin test reporter version

---

CHANGELOG.md
ext/byebug/breakpoint.c
ext/byebug/byebug.c
ext/byebug/byebug.h
ext/byebug/context.c
ext/byebug/locker.c
ext/byebug/threads.c

On my last pullrequest (#443), I fixed conflict with debase by renaming context initializer functions(e.g. Init_context() => Init_byebug_context()).
But I missed to fix other functions to conflict with debase's, for example Init_breakpoint(). So breakpoint isn't worked when using with debase.
I fixed it on this PR. On this PR, we can use byebug with debase completely.
Fixed point(rename) is the following
* Init_breakpoint() => Init_byebug_breakpoint()
* conflict to https://github.com/denofevil/debase/blob/c317d87bcf48a66f25da858a9ab6d7f4c5486ee7/ext/debase_internals.h#L110
* reset_stepping_stop_points() => byebug_reset_stepping_stop_points()
* conflict to https://github.com/denofevil/debase/blob/c317d87bcf48a66f25da858a9ab6d7f4c5486ee7/ext/debase_internals.h#L79
* add_to_locked() => …

Rename functions that conflict with debase's

---

GUIDE.md

several of these lines don't match the original program, so I (think I) matched them up a bit more. not super important, but thought I'd help since byebug is my favorite tool.

small discrepancies in guide

---

.circleci/config.yml
.codeclimate.yml
.travis.yml
CONTRIBUTING.md
README.md
Rakefile
bin/ci.sh
bin/lint.sh
bin/test.sh
tasks/linter.rb

So we can keep all linters in a single place and have more control over them. Also, this will make a potential future migration to Gitlab easier.

Remove codeclimate for linting

---

test/minitest_runner_test.rb
test/support/utils.rb

Otherwise `bundler` can error because the required version of `simplecov` (or any of its dependencies), don't match the one in the `Gemfile`.

Don't require simplecov when running a bundled env

---

.travis.yml
test/remote_debugging_test.rb

I don't have an macOS machine to investigate, so I'm skipping it for
now.

Skip failing test on macOS

---

.rubocop.yml
CHANGELOG.md
README.md
byebug.gemspec
lib/byebug/commands/break.rb
lib/byebug/commands/info/breakpoints.rb
lib/byebug/helpers/frame.rb
lib/byebug/helpers/string.rb
lib/byebug/interfaces/local_interface.rb
lib/byebug/printers/base.rb
lib/byebug/settings/callstyle.rb
lib/byebug/version.rb
test/support/test_case.rb
test/support/utils.rb

I stopped testing on MRI 2.2 a while ago. Now I'm officially dropping support by preventing installation under that ruby.

Drop 2.2 support

---

CONTRIBUTING.md
README.md
test/remote_debugging_test.rb

I don't have macOS, so I won't have a look at this unless someone buys me a mac. Contributions to get this added back welcome!

Stop testing on macOS

---

appveyor.yml

I don't think it's necessary now, and it causes issues when adding dependencies.

Remove force_ruby_platform setting from appveyor

---

test/remote_debugging_test.rb

This test case was introduced as a regression test of
https://github.com/deivid-rodriguez/byebug/issues/274
in https://github.com/deivid-rodriguez/byebug/pull/406.
The description of issues/274 says an exception will be raised
if the byebug CLI is terminated when main program is sleeping.
Before this commit there are 2 breakpoints (`byebug` method call)
before `sleep 3` and `"cont"` is called once because the arugment of
`remote_debug_connect_and_interrupt` is `"cont"`.
I think this is not intended.
And the method name of test case is `program_with_two_breakpoints`,
on the other hand the program had 3 breakpoints (`byebug`).

Make `program_with_two_breakpoints` has exactly 2 breakpoints

---

Rakefile
docker/manager.rb

The nightly CircleCI job that I added in #518 was not working, but the failure went undetected. This PR makes the failure surface. I'll fix the failure separately.

Fix some exit codes

---

CHANGELOG.md
lib/byebug/commands/break.rb
test/commands/break_test.rb
test/commands/help_test.rb

Use "<" and ">" for placeholders.

Improve `break` help text

---

CHANGELOG.md
lib/byebug/attacher.rb
lib/byebug/commands/continue.rb
lib/byebug/core.rb
test/commands/continue_test.rb
test/runner_against_program_with_byebug_call_test.rb

The `continue!` command was not ignoring further `byebug` calls as expected.
```
$ ruby -r byebug sum.rb 
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}"
(byebug) c!
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}"
(byebug) c!
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
5:   sum += i
6: end
7: 
8: byebug
=> 9: puts "Sum is #{sum}"
(byebug) c!
Sum is 1
```
```
$ RUBYOPT=-Ilib ruby -r byebug sum.rb 
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}" …
```

Fix `continue!` with byebug calls

---

CHANGELOG.md
lib/byebug/commands/skip.rb
test/commands/skip_test.rb

The new `skip` command was autolisting code for intermediate skipped breakpoints.
```
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}"
(byebug) skip
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}"
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
5:   sum += i
6: end
7: 
8: byebug
=> 9: puts "Sum is #{sum}"
(byebug)
```
```
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do |i|
4:   byebug
=> 5:   sum += i
6: end
7: 
8: byebug
9: puts "Sum is #{sum}"
(byebug) skip
[1, 9] in /home/deivid/Code/byebug/sum.rb
1: sum = 0
2: 
3: 2.times do …
```

Fix `skip` output

---

test/support/utils.rb

`test_block` was not being properly reset in some cases, and was being leaked to other tests.
See for example https://circleci.com/gh/deivid-rodriguez/byebug/9843?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.
Tentatively fixes #428.

Fix intermittent test hang

---

test/runner_against_valid_program_test.rb

Since https://github.com/ruby/ruby/commit/559dca509d2a98584b09c7d9a6d74749ce793ad7, `irb` (which we load) loads `rdoc`, which in turn loads `abbrev`.
That means the previous version of this test was broken.
Fix it by using a file under our control, so that external changes to the language don't break our suite.

Use a file in our control to test the -r flag

---

CHANGELOG.md
ext/byebug/byebug.c
test/post_mortem_test.rb

After https://github.com/ruby/ruby/commit/1998039ea4f867583d7e37ce200a88490707c330, our post mortem debugging partially broke, because ruby started emitting two `:raise` events when an exception would happen during a `load` call. In this situation, the second `:raise` event would overwrite the first one, and the context location would be incorrect, leaving the user in an unexpected location.
We fix the issue by watching for the case where we have already saved the context to the raised exception, and avoiding the overwrite.
Fixes #165.

Fix post mortem location after exception inside `load`

---

.rubocop.yml

So that rubocop upgrades never break our CI.

Explicit, disabled by default rubocop config

---

ext/byebug/byebug.c
test/commands/next_test.rb

A while ago, we used to provide the same handler for `:call`, `:b_call`, and `:class` events. At that time, we need to make this exception because `:b_call` events don't include `method_id` at the top level.
Nowadays, this is part of the `:call` handler, while the other events are handled separately. So the tracepoint information always include the `method_id` and we can remove the workaround.

Remove old workaround

---

Gemfile.lock
bin/setup.sh

CI is failing on some rubygems code, and the issue seems fixed on the latest prereleases, so upgrading.

Use prereleases of rubygems and bundler

---

.github/workflows/build.yml

I noticed that CI didn't run for #605. I think this will fix it.

Run CI on PRs too

---

ext/byebug/context.c

When compile byebug with ruby 2.7.0rc2 these warnings are shown.
This is caused by
https://git.ruby-lang.org/ruby.git/commit/?id=703783324c16b8b2b50210d1a7d1119902abbb8b
Then wrapping first and third arguments of rb_ensure with wrapper functions.
```
../../../../ext/byebug/context.c:190:20: warning: incompatible pointer types passing 'VALUE (struct call_with_inspection_data *)'
(aka 'unsigned long (struct call_with_inspection_data *)') to parameter of type 'VALUE (*)(VALUE)'
(aka 'unsigned long (*)(unsigned long)') [-Wincompatible-pointer-types]
return rb_ensure(open_debug_inspector, (VALUE)data, close_debug_inspector,
^~~~~~~~~~~~~~~~~~~~
/Users/yuichirokaneko/.rbenv/versions/2.7.0-rc2/include/ruby-2.7.0/ruby/ruby.h:1990:24: note: passing argument to parameter here
VALUE …
```

Fix compile warnings on ruby 2.7.0rc2

---

ext/byebug/context.c

argc of rb_define_singleton_method means the number of parameters
excluding klass itself. On the other hand dt_inherited expects
only klass as arguments. Then 0 is appropriate in this case.

Fix argc of rb_define_singleton_method for dt_inherited

---

test/commands/thread_test.rb

Format of `Thread#to_s` was changed by
https://git.ruby-lang.org/ruby.git/commit/?id=8a80bfcfd4d510a20a62e21d8d2f4119cb823d4f
This commit relaxes regexp of the test case.
```
$ RBENV_VERSION=2.6.5 ruby -e 'p Thread.new { while true do sleep 1 end}'
#<Thread:0x00007fb1818fc9f8@-e:1 run>
$ RBENV_VERSION=2.7.0-rc2 ruby -e 'p Thread.new { while true do sleep 1 end}'
#<Thread:0x00007f7f29889640 -e:1 run>
```

Fix test_thread_list_shows_all_available_threads on ruby 2.7.0rc2

---

Gemfile.lock

These test cases fails if we run test on ruby 2.7.0rc2.
* Byebug::MinitestRunnerTest#test_runs
* Byebug::MinitestRunnerTest#test_with_seed_option
* Byebug::MinitestRunnerTest#test_combinations
* Byebug::MinitestRunnerTest#test_per_test
* Byebug::MinitestRunnerTest#test_per_test_class
The cause is that json-2.2.0 shows warnings about
keyword parameters like
```
/Users/yuichirokaneko/ruby/byebug/vendor/bundle/ruby/2.7.0/gems/json-2.2.0/lib/json/common.rb:156: warning: The last argument is used as keyword parameters
```
Then update json gem to fix these test cases.

Update json gem to fix tests on ruby 2.7.0rc2

---

test/minitest_runner.rb

Make it clear to the user when they happen, and increase the value in seconds a bit.

Improve test suite timeouts

---

test/minitest_runner.rb

If using our minitest runner, it's more handy to specify options directly (`bin/minitest --verbose`). But if used through the rake task, supporting `TESTOPTS` is useful.
This PR gives priority to `TESTOPTS` if given.

Support TESTOPTS in our minitest runner

---

.github/workflows/fedora.yml
CHANGELOG.md
lib/byebug/core.rb

This fixes byebug usage in Fedora. Fedora's rubygems uses a switch to prevent compiled extensions from being installed into each gem's lib/ directory (`Gem.install_extension_in_lib = false`). So byebug doesn't properly work there.
Going back to a require fixes the issue.

Go back to a full `require` for requiring the extension

---

test/runner_against_program_with_byebug_call_test.rb

On Debian, while we are transitioning between Ruby versions, we have
both the old ruby (e.g. ruby2.5 and ruby2.7) and the new coinstalled,
and we want to test stuff against both of them.

runner_against_program_with_byebug_call_test: call the correct ruby

---

test/printers/plain_test.rb
test/rc_test.rb
test/runner_against_valid_program_test.rb
test/runner_without_target_program_test.rb
test/support/test_case.rb

In Debian and in other QA efforts, one might want to run the test suite
against the code that is installed on the system (as opposed to the one
in the source tree). Using require_relative like this prevents that from
working.

test: drop usage of require_relative to code in lib

---

.github/workflows/daily.yml
.github/workflows/ubuntu.yml

We want to find out about changes in ruby that break our test, but don't want those changes to make status checks fail for every PR.
So run head build on a daily basis.

Move head build to daily

---

.github/workflows/ubuntu.yml
test/test_helper.rb

Ruby's coverage library no longer supports `TracePoint` events :(
See https://bugs.ruby-lang.org/issues/16776.

Stop tracking coverage on newer rubies

---

test/minitest_runner.rb

Use Ctrl-C locally, and rely on CI's handling in CI instead.

Remove timeouts from test runner

---

.github/workflows/windows.yml
README.md

Improve Windows CI

---

test/support/simplecov.rb
test/support/utils.rb
test/test_helper.rb

I disabled it in https://github.com/deivid-rodriguez/byebug/pull/659, but it was still getting activated in some places.

Avoid simplecov on new rubies

---

CHANGELOG.md
lib/byebug/interfaces/local_interface.rb
test/runner_against_valid_program_test.rb

When IRB from ruby 2.7 is loaded, it installs a Readline completion proc
that assumes IRB is running (and crashes otherwise). Workaround this by
clearing the Readline completion when using it directly.
Fixes #654

Fix crash on TAB under ruby 2.7

---

.github/workflows/windows.yml
CHANGELOG.md
lib/byebug/interfaces/local_interface.rb

Fix 11.1.2 regression 

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
.rubocop.yml
CHANGELOG.md
README.md
Rakefile
byebug.gemspec
docker/manager.rb
lib/byebug/helpers/parse.rb
test/commands/break_test.rb
test/commands/debug_test.rb

Since it has reached its End of Life period: https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/.

Drop ruby 2.4 support

---

lib/byebug/helpers/parse.rb

* Use Ripper as it is a standard library.
* Another possibility would be to use eval() like this:
```ruby
catch(:valid) do
eval("BEGIN{throw :valid, true}\n#{code}")
false
end
```
as done in https://github.com/banister/method_source/blob/836d7047ab/lib/method_source/code_helpers.rb#L66-L80
But that means creating AST nodes, etc and seems heavier.
While trying byebug on TruffleRuby, I found this is the first issue. This change seems to fix it.
The next issue is supporting the TracePoint `:call` event in TruffleRuby: https://github.com/oracle/truffleruby/issues/1672.

Add a fallback for syntax_valid? if RubyVM is not defined

---

ext/byebug/byebug.c

Replacing `Document-class: Byebug` with `Document-module: Byebug` in `ext/byebug/byebug.c` fixes `yard doc`. Without this, it appears that YARD clobbers everything except what's in the C files. At the time of writing, https://rubydoc.info/gems/byebug contains only the following:
* Byebug (module)
* DebugThread < Thread
* ThreadsTable < Object
* Context < Object
* Exception
* Kernel
* ThreadsTable < Object
This is missing almost all the Ruby classes. This change un-confuses YARD, resulting in documentation for the Ruby code.

Unclobber YARD docs generation

---

CHANGELOG.md
lib/byebug/helpers/eval.rb
lib/byebug/helpers/var.rb

When accessing `$SAFE`, ruby 2.7 will print a warning about it becoming a regular global variable. While this might help users relying on the previous special functionality, I don't think it's useful in the context of listing global variables inside a debugger.

Skip warning about `$SAFE` global variable

---

ext/byebug/breakpoint.c

Closes #739.
This MR modifies `brkpt_set_hit_condition` in `ext/byebug/breakpoint.c` to allow clearing a breakpoint's hit condition by setting it to nil. The documentation on the function indicates this should be possible, but passing nil will raise an exception, and no code path in the function will set the condition to `HIT_COND_NONE`.

Allow Breakpoint#hit_condition=(nil)

---

CHANGELOG.md
lib/byebug/commands/break.rb
test/commands/break_test.rb
test/commands/help_test.rb

Makes it easier to create breakpoints with just `break` or `b`, like in GDB.

Break at current line when `break` has no arguments

---

lib/byebug/commands/info.rb
lib/byebug/commands/step.rb
lib/byebug/commands/tracevar.rb
lib/byebug/helpers/reflection.rb
lib/byebug/history.rb
test/commands/finish_test.rb
test/commands/help_test.rb
test/commands/history_test.rb
test/commands/info_test.rb
test/commands/quit_test.rb
test/commands/set_test.rb
test/support/temporary.rb

Minor improvements to consistency of instance variables in `Byebug::History` to better match Ruby conventions.
I also searched for typos using [cspell](https://www.npmjs.com/package/cspell). I manually fixed the obvious typos that were reported (and ignored tons of false positive matches).

Remove unneeded selfs in Byebug::History and fix typos

---

.github/workflows/daily.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

Our build is fast, so we don't need it.

Don't fail fast in CI

---

.github/workflows/windows.yml

Windows sometimes hangs so this is most useful there.

Add `timeout-minutes` to Windows workflow

---

CHANGELOG.md
lib/byebug/commands/where.rb
test/commands/where_test.rb

When the frame stack is too deep it's useful pass an argument to `where` to print the nth most recent frames. This pull request replaces  my previous one #681 which had a typo.

Pass argument to `where` to print the nth first frames

---

.github/FUNDING.yml

Included your github sponsors and liberapay accounts. 
Which would you prefer adding to `funding_uri` in the gemspec?

Add more options to FUNDING.yml
